### ISSUE TITLE
Crash with Guitar Hero I songs

### ISSUE THREAD

**Issue by 3v1n0** [fofix/fofix#21] opened 2014-01-15 13:58 UTC
Hi, I've just installed FoFix git, with new configuration folder, but when trying to open a Guitar Hero I song I'm getting a crash due to:

```
File "/home/marco/Giochi/FoFix/src/views/Dialogs.py", line 1274, in keyPressed
    self.players[i].difficulty = self.info.partDifficulties[self.players[i].part.id][self.selected[i]]
IndexError: list index out of range
```

After some debugging, it seems that self.info.partDifficulties[self.players[i].part.id] is an empty list here.

All works using 3.121 provided by ubuntu repositories instead.

**Comment by Linkid** [comment] 2015-07-01 16:46
Hi!
I had the same problem and I found this thread on the Frets On Fire Forum, which gives a temporary working solution : http://www.fretsonfire.net/forums/viewtopic.php?f=32&t=49493.
I'm looking at the code to find what is wrong with those musics.

**Comment by mdsitton** [comment] 2015-07-01 18:50
I don't currently have a running fofix environment on the computer im currently on, but i don't think i have any songs where i can test this. If you mention a song that this effects, it may help track it down.

**Comment by mdsitton** [comment] 2015-07-01 18:58
Also @Linkid just thought i would mention it here since you've replied here even if its a bit off topic...

I see you forked my fofix-rewrite repo. I just made an issue about what the current status of it is here.
https://github.com/mdsitton/fofix-rewrite/issues/2

**Comment by Linkid** [comment] 2015-07-01 21:30
@mdsitton: you can reproduce that issue with Guitar Hero 1 songs (found them there : http://www.fretsonfire.net/forums/viewtopic.php?f=5&t=57307).
And ok for your other repo. I didn't know if it was still in development. Thanks.

**Comment by wrzwicky** [comment] 2017-09-25 11:03
I think I've fixed this. My pull request has the patch, but if you want to fix your own code: See song.py line 137; there is a comma missing between "T1 GEMS" and "Click". Corrected line is:
  GUITAR_PART: Part(GUITAR_PART, _("Guitar"), ["PART GUITAR", "T1 GEMS", "Click", "Midi Out"]),
The game works with GH1 songs, though the background music doesn't play. But this issue should be fixed now.

**Closed** 2017-11-02 08:29 UTC
Labels: bug
