### ISSUE TITLE
Separated files for song infos and scores

### ISSUE THREAD

**Issue by Salamandar** [fofix/fofix#36] opened 2015-08-09 14:19 UTC
Hi there !
It'd be great to have separated files for song infos (Name/Artist/Order in Tier) and for scores.
That would be great for sharing a song with or without scores.
For example I made a git repo with all my musics (without audio files) (github.com/Salamandar/FoF-Musics) and I don't want my scores being overwritten each time someone creates a new music.

**Comment by mdsitton** [comment] 2015-08-09 16:22
This had already been planned at some point.
Here is a link to the issue in the old bug tracker.

https://code.google.com/p/fofix/issues/detail?id=346

**Comment by Salamandar** [comment] 2015-08-09 17:34
Okay ! But didn't you copy the old bug reports to Github ? ^^
Anyways, I'll look into the code to see what changes are necessary.

**Comment by mdsitton** [comment] 2015-08-12 18:12
They never were transferred over, we moved from google code way before google provided a transfer service. (plus i tried the transfer thing on the repo and there was to many issues and it wouldn't have worked right anyways) I have exported the issues, and they are in a JSON format somewhere on my desktop, so maybe at some point that could be used for something.

**Comment by mdsitton** [comment] 2015-08-12 18:16
Another thing that basically all of the guys that were around then working on FoFiX are no longer around, and of the few of us that are around are quite stretched for time. So this and many other things probably wont be implemented any time soon, unless we have more time to work on it again. :(

**Comment by Salamandar** [comment] 2015-08-12 22:56
Okay. How many "almost full time" devs are working ?
I'd love to work on it, but i don't have a lot of time neither.
By the way, what are the most "important" features your are working on now ? Do you still want to port it piece by piece to C ?

**Comment by mdsitton** [comment] 2015-08-14 20:21
Currently really no one, I try to work on it a couple times a year at least to show that i haven't completely abandoned the project. @stump really does want to work on it still, he just hasn't been able to find the time. Other than that for previous people since i began working on FoFiX:

I know @nhydock has gone on to bigger things (looks to be getting a game he made called Storymode on steam) Plus on his linkedin page he has listed his involvement with FoFiX as: 2008 – January 2013. At one point he had expressed how he thought it was always difficult to understand FoFiX's code, later realizing not all games are that way and that the code is just bad :P (just vaguely from what I remember probably not his exact words)

Then there is @akedrou seems to always stop by and drop a random commit or two every few years.

Lastly for a while we had @upgradeadvice aka fuzion, but he hasn't been around since 2011.


Well we have decided one thing, this project will stay python. We do have a few C and Cython extension modules, but most of the code is python. Moving something to C or Cython has been done on a case by case basis if we think that its worth the effort. This was basically confirmed by stump and I in IRC a few weeks ago, and that if a fully C++ project was started he wouldn't be contributing.

With that said, I am not against starting a C++ rewrite(this was being discussed in IRC a bit before the above conversation happened), in-fact i started one with someone else,  but the guy bailed when he decided he didn't really know C++ well enough.(We didn't get to far really) Its currently in a private github repo though, main thing it needs is a decent name, and I need to give it a license then i will open up the repo. 

So... i think thats it for now lol

**Comment by mdsitton** [comment] 2015-08-14 20:25
And one last thing, if any one project happens to retain more than just me working on it I am likely to work on that project a ton more. So if a couple of people(ideally 3+ people including me) want to get active contributing to FoFiX, or even help me with that C++ project i can probably find the time to work on it pretty often.

**Comment by Salamandar** [comment] 2015-08-15 00:27
Okay for all of that.
To be fair :
* The actual project is pretty much a mess. Some parts are very buggy and lots of code have been badly written and we wouldn't read them anymore.
* The project could be more structured.
* I don't know a lot to Python (I can debug Python, i wrote a very small script, but that's all)
* I just began to learn C++ (with a very good C base), it's pretty hard to learn but I like it, I think
* I think you know Phase Shift. Closed source, windows only. Written in C++. They don't want to be open-source because "they want to keep control on PS and don't become a mess like FoF(iX)". That is not a good reason to stay closed source, and I am writing a message to them trying to explain that they CAN be open source (= bug tracking, linux port, features+++, etc) AND have a control on their code and stay "proprietary" if they want. (Well, we can find .NET code on Github……).
Would you like to work on the PS base ? I would.

And I completely agree with your last message : If we are only 2 on a brand new c++ project, I don't think I would work a lot on this. but yeah, 3/4 would be great for a start.

**Comment by mdsitton** [comment] 2015-08-15 07:50
So regarding trying to get the phase shift source code, and the reasons its not open source see this post:
http://dwsk.proboards.com/post/13226/thread

Mainly his code is a mess as well, and he doesn't want to explain why to others...

**Comment by mdsitton** [comment] 2015-08-15 07:53
And also, not fully sure if this is exactly what he meant, but it looks like he would even be willing to setup shop with a few people and start fresh.

**Comment by Salamandar** [comment] 2015-08-16 15:26
Hmmm yeah, i can see that. Well, maybe that's the best for both projects to start fresh and new :)

**Comment by Salamandar** [comment] 2015-08-20 16:28
![img_20150820_182423](https://cloud.githubusercontent.com/assets/6552989/9388987/ee97ca18-4768-11e5-8dc7-3bb1e261bfb1.jpg)
Here is just a thought.
I may work on the "file listing" part : it's easy and it doesn't rely on any other part (but the other parts would need this one).
What do you think ? I may rewrite it here : https://lite6.framapad.org/p/fofix

**Comment by mdsitton** [comment] 2015-08-20 18:17
Its a bit difficult to read some of that, so rewriting that might be a good idea.

Btw, i have my own etherpad-lite instance running here:
https://msitton.com/pad/

**Comment by mdsitton** [comment] 2015-08-20 23:20
Actually i just realized we already have an issue for this here on github...
issue #2

**Comment by Salamandar** [comment] 2015-08-21 18:53
Well I'm not sure that storing the scores in a DB (outside the music folder) is the best solution…
For example I have 2 PCs where I play FoFiX, and the musics are not at the same location. And I still want to "sync" the scores.
But maybe I don't see the advantages of this.

By the way I kinda started some code (VERY bad code for a good start xD) here
https://github.com/Salamandar/FoF-
For now I just scan the folder and print all the files (with a "/" for the folders) recursively.
This is very fast, not like FoF. xD

**Comment by Salamandar** [comment] 2015-08-21 19:36
By the way, that's great for etherpad :) I'm okay to use yours.

I just finished the "music detection on song.ini existence".

**Comment by mdsitton** [comment] 2015-08-27 16:23
I also just so you know, I went ahead and made the github repo public for my c++ code. However as a warning I have yet to decide one way or the other on a license.
https://github.com/mdsitton/musicgame

If you wanted to continue this i suggest the conversation be moved elsewhere...

**Closed** 2018-12-18 20:02 UTC
Labels: enhancement
