### ISSUE TITLE
change python version

### ISSUE THREAD

**Issue by annopnod** [fofix/fofix#218] opened 2020-05-26 13:55 UTC
fofix use  python version 2.7
change  to   python version 3
![Screenshot from 2020-05-26 20-55-03](https://user-images.githubusercontent.com/6957642/82909237-31a30e80-9f93-11ea-8c5d-72c11f3835a1.png)

**Comment by AEFeinstein** [comment] 2020-05-26 14:00
Duplicate of #110, this should be closed

**Comment by Linkid** [comment] 2020-05-26 17:03
Agreed

**Closed by Linkid** 2020-05-26 17:03 UTC
Labels: bug

**Comment by Linkid** [comment] 2020-05-26 17:06
@annopnod : thank you for your issue. Don't hesitate to look at issues already open and to participate in it ;).
